apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    initContainers:
        - name: init-db-ip
          image: busybox
          command:
              [
                  "sh",
                  "-c",
                  "until nslookup postgres-service.default.svc.cluster.local; do echo waiting for postgres-service; sleep 2; done; ",
              ]
    containers:
        - name: myapp-container
          image: node:alpine
          env:
              - name: POSTGRES_IP
                value: postgres-service
          ports:
              - containerPort: 3000
