apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        tier: backend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: cka-demo
    template:
        metadata:
            labels:
                app: cka-demo
        spec:
            containers:
                - name: nginx
                  image: nginx:1.23.0
                  ports:
                      - containerPort: 80
