apiVersion: v1
kind: Pod
metadata:
    name: redis
spec:
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: disktype
                            operator: In
                            values:
                                -
    containers:
        - name: redis
          image: redis
