apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: "2024-07-09T06:59:10Z"
    labels:
        run: nginx
    name: nginx
    namespace: default
    resourceVersion: "78141"
    uid: 0022ae7f-1e45-40eb-bd05-f6ef1afb51a1
spec:
    containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: kube-api-access-bnwr4
                readOnly: true
    nodeName: cka-cluster-worker2
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: kube-api-access-bnwr4
          projected:
              defaultMode: 420
              sources:
                  - serviceAccountToken:
                        expirationSeconds: 3607
                        path: token
                  - configMap:
                        items:
                            - key: ca.crt
                              path: ca.crt
                        name: kube-root-ca.crt
                  - downwardAPI:
                        items:
                            - fieldRef:
                                  apiVersion: v1
                                  fieldPath: metadata.namespace
                              path: namespace
status:
    phase: Pending
    qosClass: BestEffort
