apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: example-cronjob
spec:
    schedule: "*/1 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: task-container
                          image: busybox
                          command: ["echo", "Hello from the cron job"]
                    restartPolicy: Never
