apiVersion: apps/v1
kind: Deployment
metadata:
    name: ngnix-deployment
    namespace: app-space
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ngnix
    template:
        metadata:
            labels:
                app: ngnix
        spec:
            containers:
                - name: ngnix
                  image: nginx:1.23.4-alpine
                  ports:
                      - containerPort: 80
