apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs-nginx
spec:
    replicas: 4 #Updated from 3 to 4
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: nginx
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                      - containerPort: 80
